components:
  schemas:
    Item:
      type: object
      properties:
        timestamp:
          type: string
          example: '2019-04-02T18:32:16.340Z'
    Collection:
      type: object
      properties:
        timestamp:
          type: string
          example: '2019-04-02T18:32:16.340Z'
        page:
          type: object
      
      
