components:
  schemas:
    Item:
      type: object
      properties:
        timestamp:
          type: string
          example: '2019-04-02T18:32:16.340Z'
          
    Collection:
      type: object
      properties:
        timestamp:
          type: string
          example: '2019-04-02T18:32:16.340Z'
        page:
          $ref: '#/components/schemas/Page'
          
    Page:
      type: object
      properties:
        has_next: 
          type: boolean
          example: true
        has_prev:
          type: boolean
          example: false
   
    Error:
      type: object
      properties
        timestamp:
          type: string
          example: '2019-04-02T18:32:16.340Z'
        status:
          type: integer
          example: 500
      
    Validation:
      type: object
      properties
        timestamp:
          type: string
          example: '2019-04-02T18:32:16.340Z'
        status:
          type: integer
          example: 422
   
      
